export const FETCH_SOURCES = 'FETCH_SOURCES';
export const FETCH_NEWS = 'FETCH_NEWS';
export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const SELECTED_NEWS = 'SELECTED_NEWS';
export const SELECTED_CHANNEL = 'SELECTED_CHANNEL';
export const HEADLINE_FETCH_ERROR = 'HEADLINE_FETCH_ERROR';
export const SOURCE_FETCH_ERROR = 'SOURCE_FETCH_ERROR';